### ISSUE TITLE
unable to save data via plugin

### ISSUE THREAD

**Issue by alikon** [joomla-extensions/jstats-server#11]
i've cloned a jstats-server and installed on localhost
with some dummy data on jos_jstats table
 pinging http://localhost/jstats-server/www/  works

```
{"data":{"php_version":{"5.6":100},"db_type":{"MS SQL":100},"db_version":{"11.":100},"cms_version":{"3.3.3":100},"server_os":{"Mac":100},"total":1}}
```

i've installed the jstats plugin on a localhost joomla site with this ```JUri('http://localhost/jstats-server/www/submit')```

but when sends data to jstats-server

```
{"error":true,"message":"Unable to locate controller `Stats\\Controllers\\SubmitControllerCreate`."}
```

what i'm doing wrong?

**Comment by wilsonge** [comment]
@mbabker

**Comment by mbabker** [comment]
WTF!?  Why on earth does the router append the HTTP verb for EVERYTHING BUT POST!?

**Comment by wilsonge** [comment]
Put and Patch both go to update as well :P So it's not JUST post :P

**Comment by mbabker** [comment]
![inconsistencies](https://cloud.githubusercontent.com/assets/368545/9442224/c2276fdc-4a48-11e5-8d0e-95d4d451b53b.jpg)

**Comment by alikon** [comment]
just another small one 
after applying the patch got this from plugin 
```
	$status = $http->post($uri, $data, null, 2);
```
```
{"error":true,"message":"Key Stats\\Controllers\\SubmitControllerCreate has not been registered with the container."}
```
so i've changed
https://github.com/joomla-extensions/jstats-server/blob/master/src/Providers/ApplicationServiceProvider.php#L10
https://github.com/joomla-extensions/jstats-server/blob/master/src/Providers/ApplicationServiceProvider.php#L91
https://github.com/joomla-extensions/jstats-server/blob/master/src/Providers/ApplicationServiceProvider.php#L94

but still no luck

got this

```
object(JHttpResponse)#109 (3) { ["code"]=> int(500) ["headers"]=> array(6) { ["Date"]=> string(29) "Mon, 24 Aug 2015 18:26:37 GMT" ["Server"]=> string(45) "Apache/2.4.7 (Win32) OpenSSL/1.0.1e PHP/5.5.9" ["X-Powered-By"]=> string(9) "PHP/5.5.9" ["Content-Length"]=> string(1) "0" ["Connection"]=> string(5) "close" ["Content-Type"]=> string(9) "text/html" } ["body"]=> string(0) "" }
```

**Comment by mbabker** [comment]
Turn on error reporting in the configuration.  `display_errors` is turned off if the error reporting value is 0 (which it defaults to in the dist config file).

**Comment by alikon** [comment]
thx @mbabker  for the tip
i've discovered some timeout due to my wrong settings
now it works ```{"error":false,"message":"Data saved successfully"}```

it's time for me to do some benchmark...
