### ISSUE TITLE
Proposal - Have the server act as a RESTful API

### ISSUE THREAD

**Issue by mbabker** [joomla-extensions/jstats-server#6]
Long and short, instead of having an HTML frontend, I think it'd be interesting to just have the server act as a RESTful API provider and kick back sanitized data from its various endpoints.

### Why?
If we're going to collect the data, we should share it (within practical and legal reason).  WordPress' stats are consumable via an HTML page and API and only kicks back summarized top level data (for example the percentage of installs on MySQL 5.1, not specific counts).

Also, in lieu of web services support in the CMS, this at least demonstrates some way to use Joomla code as an API provider, even in the most simplest of forms.

### Raw Data Access
Arguably there will be folks with a valid reason to get the detailed raw data.  This could be implemented through some sort of authorization token that when passed returns a more detailed dataset.

### Rendering the Data
Since this would be an API, someone could code up a module to use on any Joomla web property to take the data and plug it into a chart.

**Comment by mbabker** [comment]
I'm going to take no response as a sign of no interest.  Moving on then.

**Comment by wilsonge** [comment]
If someone wants to write the code sure go for it. But personally I don't see it as being hugely important - especially for a first step

**Comment by mbabker** [comment]
Actually it's a large architectural decision in how the server is deployed, how the plugin interfaces with it, and how Joomla shares the data.
